server:
  port: 9001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        shared-dataids: mysql.yml
        refreshable-dataids: mysql.yml
  application:
    name: panda-user-service
  profiles:
    active: dev
-- bootstrap.yml

-- bootstrap-dev.yml
spring:
  cloud:
    nacos:
      config:
        namespace: 5f6ec9ff-5dfb-47a5-95fe-91fc00f7d732
      discovery:
        namespace: 5f6ec9ff-5dfb-47a5-95fe-91fc00f7d732
        
 <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
                <version>0.2.2.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
                <version>0.2.2.RELEASE</version>
            </dependency>
             <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.9</version>
        </dependency>



111111111111111111111
             <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        
        
mysql
-----
spring:
  quartz:
    job-store-type: jdbc
      #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456789
    max-idle: 10
    min-idle: 5
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      minimum-idle: 0
    redis:
      host: 127.0.0.1
      port: 6379
      password:

    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
    http:
      multipart:
        max-file-size: 1000MB
        max-request-size: 1000MB
    zipkin:
      base-url: http://localhost:5001
redis:
  cache:
    expiration: 3601
ribbon:
  eager-load:
    enabled: true
    clients: panda-auth,panda-user-service
  Httpclient:
    enabled: true
  OkHttp:
    enabled: false
  ReadTimeout: 10000
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: false
  httpclient:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#关闭验证
management:
  metrics:
    web:
      server:
        auto-time-requests: false
